### ISSUE TITLE
Batch Geocoder: Error message

### ISSUE THREAD

**Issue by BK01** [bcgov/ols-geocoder#331]
When navigating to the Batch Geocoder web app, the following error message is displayed at the top of the screen. This occurs before clients (who are using VPN) have interacted with the GUI. No fields are highlighted and the error remains even after users have filled out all fields.

This error message does not prevent users from submitting requests but has caused confusion. Based on the 500 errors shown in the dev console this may be a CPF issue (tbd).

"The form contains errors, please update the highlighted fields to fix the errors."

![image](https://user-images.githubusercontent.com/9123564/191998783-dc0b47db-58c7-416c-b8f9-4c1fb5757e26.png)

**Notes:**
- This error only appears when logged in over VPN
- This error disappears when the screen is refreshed

**Comment by bolyachevets** [comment]
I believe it is CPF/VPN related.

Depending on the browser you get slightly different error messages in the developer's console.
E.g. on Crhome:

```
multiple:13          GET https://cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css net::ERR_CERT_AUTHORITY_INVALID
multiple:28          GET https://cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js net::ERR_CERT_AUTHORITY_INVALID
multiple:30          GET https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js net::ERR_CERT_AUTHORITY_INVALID
multiple:11          GET https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css net::ERR_CERT_AUTHORITY_INVALID
multiple:12          GET https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css net::ERR_CERT_AUTHORITY_INVALID
multiple:26          GET https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js net::ERR_CERT_AUTHORITY_INVALID
multiple:24          GET https://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js net::ERR_CERT_AUTHORITY_INVALID
multiple:14          GET https://cdn.datatables.net/scroller/1.2.2/css/dataTables.scroller.css net::ERR_CERT_AUTHORITY_INVALID
multiple:15          GET https://cdn.datatables.net/plug-ins/1.10.6/integration/bootstrap/3/dataTables.bootstrap.css net::ERR_CERT_AUTHORITY_INVALID
multiple:32          GET https://cdn.datatables.net/1.10.11/js/jquery.dataTables.min.js net::ERR_CERT_AUTHORITY_INVALID
multiple:34          GET https://cdn.datatables.net/scroller/1.2.2/js/dataTables.scroller.min.js net::ERR_CERT_AUTHORITY_INVALID
multiple:36          GET https://cdn.datatables.net/1.10.11/js/dataTables.bootstrap.min.js net::ERR_CERT_AUTHORITY_INVALID
multiple:42          GET https://apps.gov.bc.ca/pub/cpf/js/ws.js;jsessionid=85323FB5FA7909877617CDB1EC0DAE2C net::ERR_ABORTED 500 (Internal Server Error)
multiple:17          GET https://apps.gov.bc.ca/pub/cpf/css/cpf.css;jsessionid=85323FB5FA7909877617CDB1EC0DAE2C net::ERR_ABORTED 500 (Internal Server Error)
multiple:16          GET https://apps.gov.bc.ca/pub/cpf/css/rs.css;jsessionid=85323FB5FA7909877617CDB1EC0DAE2C net::ERR_ABORTED 500 (Internal Server Error)
multiple:40          GET https://apps.gov.bc.ca/pub/cpf/js/admin.js;jsessionid=85323FB5FA7909877617CDB1EC0DAE2C net::ERR_ABORTED 500 (Internal Server Error)
multiple:38          GET https://apps.gov.bc.ca/pub/cpf/js/rs.js;jsessionid=85323FB5FA7909877617CDB1EC0DAE2C net::ERR_ABORTED 500 (Internal Server Error)
multiple:18          GET https://apps.gov.bc.ca/pub/cpf/css/bcgov.css;jsessionid=85323FB5FA7909877617CDB1EC0DAE2C net::ERR_ABORTED 500 (Internal Server Error)
multiple:216 Uncaught TypeError: $(...).rules is not a function
    at HTMLDocument.<anonymous> (multiple:216:106)
    at i (jquery-1.12.1.min.js:2:27451)
    at Object.fireWith [as resolveWith] (jquery-1.12.1.min.js:2:28215)
    at Function.ready (jquery-1.12.1.min.js:2:30008)
    at HTMLDocument.K (jquery-1.12.1.min.js:2:30370)
(anonymous) @ multiple:216
i @ jquery-1.12.1.min.js:2
fireWith @ jquery-1.12.1.min.js:2
ready @ jquery-1.12.1.min.js:2
K @ jquery-1.12.1.min.js:2

```
In Safari:

```
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (ws.js;jsessionid=9903D8F1A9D1AADA92BB1098570BDEEA, line 0)
[Error] Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “maxcdn.bootstrapcdn.com” which could put your confidential information at risk. (bootstrap.min.css, line 0)
[Error] Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “cdn.datatables.net” which could put your confidential information at risk. (dataTables.scroller.css, line 0)
[Error] Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “ajax.aspnetcdn.com” which could put your confidential information at risk. (jquery.validate.min.js, line 0)
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (rs.css;jsessionid=9903D8F1A9D1AADA92BB1098570BDEEA, line 0)
[Error] Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “cdn.datatables.net” which could put your confidential information at risk. (dataTables.bootstrap.css, line 0)
[Error] Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “maxcdn.bootstrapcdn.com” which could put your confidential information at risk. (font-awesome.min.css, line 0)
[Error] Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made. (jasny-bootstrap.min.css, line 0)
[Error] Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “cdn.datatables.net” which could put your confidential information at risk. (jquery.dataTables.min.js, line 0)
[Error] Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “maxcdn.bootstrapcdn.com” which could put your confidential information at risk. (bootstrap.min.js, line 0)
[Error] Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “cdn.datatables.net” which could put your confidential information at risk. (dataTables.scroller.min.js, line 0)
[Error] Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “cdn.datatables.net” which could put your confidential information at risk. (dataTables.bootstrap.min.js, line 0)
[Error] Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made. (jasny-bootstrap.min.js, line 0)
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (rs.js;jsessionid=9903D8F1A9D1AADA92BB1098570BDEEA, line 0)
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (admin.js;jsessionid=9903D8F1A9D1AADA92BB1098570BDEEA, line 0)
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (cpf.css;jsessionid=9903D8F1A9D1AADA92BB1098570BDEEA, line 0)
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (bcgov.css;jsessionid=9903D8F1A9D1AADA92BB1098570BDEEA, line 0)
[Error] TypeError: $('#clientMultiple input[name=maxResults]').rules is not a function. (In '$('#clientMultiple input[name=maxResults]').rules('add', {min:1,max:1000})', '$('#clientMultiple input[name=maxResults]').rules' is undefined)
	(anonymous function) (multiple:216:112)
	i (jquery-1.12.1.min.js:2:27457)
	fireWith (jquery-1.12.1.min.js:2:28217)
	ready (jquery-1.12.1.min.js:2:30020)
	K (jquery-1.12.1.min.js:2:30376)
[Error] Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made. (bootbox.min.js, line 0)
```

Basically, CPF is trying to load resource packages from various external sources See: https://github.com/bcgov/cpf/blob/9722170b06be675700469bf8578ca7ba597ea151/cpf-api-app/src/main/resources/ca/bc/gov/open/cpf/api/web/pages.sf.xml#L87

From the error messages in the console we can see that something is wrong with certifacates.

We can simulate the problem without CPF.

Go to one of the URLs from the pages.sf.xml CPF file: https://cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css 

With VPN on you get a certificate error:

<img width="688" alt="Screen Shot 2022-09-23 at 2 26 55 PM" src="https://user-images.githubusercontent.com/22973013/192061015-4a920605-7366-46f0-9a9c-fb874ef81870.png">

Without VPN the certificate is correct:

<img width="688" alt="Screen Shot 2022-09-23 at 2 27 31 PM" src="https://user-images.githubusercontent.com/22973013/192061051-027e0e8d-b2d1-4887-8c9f-152ebee29c09.png">

**Comment by bolyachevets** [comment]
I did make a change to web.xml TomCat config file <session-config>...</session-config>
There is still the problem with certificates described above, but the issue might be partially resolved. Please test.

**Comment by BK01** [comment]
The issue no longer occurs for me following a quick test (using Chrome with VPN). I'll also ask for the bug reporter to check as well.

**Comment by BK01** [comment]
Confirmation received that the issue is no longer occurring.

**Comment by alixcote** [comment]
Hi Brian - Can we close this ticket now?
